Error: GameStore Redis Error: Error: connect ECONNREFUSED 127.0.0.1:6379     at <unknown> (Error: connect ECONNREFUSED 127.0.0.1:6379) {   errno: -111,   code: 'ECONNREFUSED',   syscall: 'connect',   address: '127.0.0.1',   port: 6379 }
Error: Redis: Retrying connection (attempt 33), delay 1650ms

You need to:

double check the code for connecting to sever , and only as connect if soket io enable only when wanting to start a remote game with a remote player , try catch any connecting errro to sever , to soket io , to redis , to anything , to send a clear messsagening error to the web app , when anything occur , never left failed errror , never !!!